version: '3'

services:
    db:
        build:
            context: .
            dockerfile: Dockerfile_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: apuser
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: subscManagement
            TZ: "Asia/Tokyo"
            BIND-ADDRESS: 0.0.0.0
        ports:
            - 3306:3306
        volumes:
            - db-data:/var/lib/mysql
        tty: true

    django:
        build:
            context: .
            dockerfile: Dockerfile_django
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        tty: true
        depends_on:
            - db

volumes:
    db-data: