version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    hostname: subsc-mysql-container
    env_file:
      - .env
    environment:
      MYSQL_USER: apuser
      MYSQL_DATABASE: subscManagement
      TZ: "Asia/Tokyo"
      BIND-ADDRESS: 0.0.0.0
    ports:
      - 3306:3306
    # データを永続化させる場合
    volumes:
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
    tty: true
    networks:
        app_net:
          ipv4_address: 172.20.0.3
      depends_on:
        - django

    django:
        build: .
        hostname: subsc-django-container
        ports:
          - "8000:8000"
        volumes:
          - ./docker_django_app:/code
        networks:
          app_net:
            ipv4_address: 172.20.0.2
        tty: true

    networks:
      app_net:
        driver: bridge
        ipam:
          driver: default
          config:
            - subnet: 172.20.0.0/24
    volumes:
      est-data: